### ISSUE TITLE
How about the generated results? Is it acceptable?

### ISSUE THREAD

**Issue by gongel** [moyix/fauxpilot#42]
Thx～

**Comment by moyix** [comment]
That's kind of a subjective question, but I think it's pretty decent. The CodeGen paper (Table 3) has some more quantitative comparisons between Codex (what Copilot uses) and CodeGen (what FauxPilot uses):

https://arxiv.org/abs/2203.13474

However, note that Codex has been updated and retrained since that paper came out, so it's not definitive as far as the quality of the code.

**Comment by gongel** [comment]
Thx for your reply. In my practice, fauxpilot always offers some not so good candidate, just like this, it uses codegen-6B-mono model.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/24390500/188640182-80eb97c5-7893-459e-a268-2750444b3221.png">

Is it a normal ？
